services:
  web:
    image: php:8.4-apache
    container_name: http_codes_ondemand
    ports:
      - "80:80"
    network_mode: bridge
    restart: on-failure
    volumes:
      - ./html:/var/www/html
